import { measureElement } from '@pixelpeeper/measure';
import type { Facts } from '@pixelpeeper/schema';
import css from './overlay.css?inline';

type Saved = { id: string; title: string; scope: 'element' | 'page'; facts: Facts };
const esc = (value: unknown) => String(value ?? 'Unavailable').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const key = 'pixelpeeper.saved.v1';

/** UI scaffold. Capture/model integration is deliberately separate from measurements. */
export function createOverlay() {
  const host = document.createElement('pixel-peeper-overlay');
  host.style.cssText = 'all:initial;font:14px/1.5 system-ui;color:#252523;color-scheme:light;display:none;position:fixed;inset:0;z-index:2147483647;pointer-events:none;contain:layout style';
  const root = host.attachShadow({mode:'open'});
  root.innerHTML = `<style>${css}</style><div class="box hover"><span class="tag"></span></div><div class="box selected"><span class="tag"></span></div>
    <div class="toolbar" hidden><button class="primary" data-action="scan">Scan selection</button><button data-action="parent">Parent</button><button data-action="child">Child</button><button data-action="clear">Clear</button></div>
    <div class="hint" hidden>Hover to preview · Click to select · Esc to exit</div><div class="scan" hidden aria-hidden="true"><div class="pixels">${Array.from({length:12},(_,i)=>`<i style="left:${8+i*17%84}%;top:${12+i*23%76}%"></i>`).join('')}</div><div class="beam"></div></div><div class="scan-label" hidden role="status"></div>
    <section class="window" hidden aria-label="Pixel Peeper workspace"><header class="head"><span class="handle">Pixel Peeper</span><button data-action="hide">Hide</button></header><div class="body"></div><footer class="foot"></footer></section>
    <div class="launcher"><button class="mascot" aria-label="Open Pixel Peeper controls" aria-expanded="false" aria-controls="menu"><span class="sprite" aria-hidden="true"></span></button><nav class="dock" id="menu" aria-label="Pixel Peeper controls"><button class="primary" data-action="pick">Pick element</button><button data-action="page">Pick whole page</button><button data-action="saved">Saved</button><button data-action="resume">Resume</button></nav></div><div class="feedback" role="status" aria-live="polite" hidden></div>`;
  // Keep the mascot first in keyboard order; place it last visually.
  const q = <T extends HTMLElement = HTMLElement>(s:string) => root.querySelector<T>(s)!;
  q('.mascot').style.order = '2'; q('.dock').style.order = '1';
  q('.sprite').style.backgroundImage = `url("${chrome.runtime.getURL('/detective-poses.png')}")`;
  document.documentElement.append(host); host.hidden = true;
  let active=false,picking=false,selected:Element|null=null,facts:Facts|null=null,scope:'element'|'page'='element';
  let saved:Saved[]=[],compare:string[]=[],run=0,destroyed=false,phase:'idle'|'selected'|'scanning'|'result'='idle',suppressResult=false;
  let menuTimer:ReturnType<typeof setTimeout>,feedbackTimer:ReturnType<typeof setTimeout>,poseTimer:ReturnType<typeof setTimeout>;
  let format:'md'|'json'|'css'='md'; const sources:Record<string,number>={Typography:0,Color:0,Shape:0,Spacing:0};
  const abort = new AbortController(), signal = abort.signal;
  void chrome.storage.local.get(key).then(data=>{if(!destroyed){saved=Array.isArray(data[key])?data[key]:[];}}).catch(()=>notify('Saved ideas could not be loaded.'));
  function notify(message:string){clearTimeout(feedbackTimer);q('.feedback').textContent=message;q('.feedback').hidden=false;feedbackTimer=setTimeout(()=>q('.feedback').hidden=true,2800);}
  function menu(open:boolean){clearTimeout(menuTimer);q('.launcher').classList.toggle('open',open);q('.mascot').setAttribute('aria-expanded',String(open));q('.mascot').setAttribute('aria-label',open?'Close Pixel Peeper controls':'Open Pixel Peeper controls');}
  function place(box:HTMLElement,el:Element|null){if(!el?.isConnected){box.style.display='none';return;}const r=el.getBoundingClientRect();Object.assign(box.style,{display:'block',left:`${r.left}px`,top:`${r.top}px`,width:`${r.width}px`,height:`${r.height}px`});const tag=box.querySelector('.tag');if(tag)tag.textContent=`${el.tagName.toLowerCase()} · ${Math.round(r.width)}×${Math.round(r.height)}`;}
  function geometry(){if(!selected?.isConnected){place(q('.selected'),null);q('.toolbar').hidden=true;if(phase==='scanning')cancel();return;}place(q('.selected'),selected);const r=selected.getBoundingClientRect();const x=Math.max(8,Math.min(r.left,innerWidth-320)),y=Math.max(8,Math.min(r.bottom+10,innerHeight-56));Object.assign(q('.toolbar').style,{left:`${x}px`,top:`${y}px`});const l=Math.max(0,r.left),t=Math.max(0,r.top),w=Math.max(0,Math.min(innerWidth,r.right)-l),h=Math.max(0,Math.min(innerHeight,r.bottom)-t);Object.assign(q('.scan').style,{left:`${l}px`,top:`${t}px`,width:`${w}px`,height:`${h}px`});q('.scan').style.setProperty('--travel',`${Math.max(0,h-4)}px`);Object.assign(q('.scan-label').style,{left:`${x}px`,top:`${y}px`});}
  function cancel(){run++;q('.scan').hidden=true;q('.scan-label').hidden=true;if(phase==='scanning')phase=facts?'selected':'idle';}
  function pick(){cancel();picking=true;q('.hint').hidden=false;q('.window').hidden=true;q('.toolbar').hidden=true;menu(false);}
  function stopPick(){picking=false;q('.hint').hidden=true;place(q('.hover'),null);}
  function select(el:Element,page=false){cancel();stopPick();selected=el;scope=page?'page':'element';facts=null;phase='selected';q('.window').hidden=true;q('.toolbar').hidden=false;geometry();menu(false);}
  const own = (event:Event) => event.composedPath().includes(host);
  document.addEventListener('mousemove',e=>{if(picking&&!own(e))place(q('.hover'),document.elementFromPoint(e.clientX,e.clientY));},{capture:true,signal});
  document.addEventListener('click',e=>{if(!active||own(e))return;menu(false);if(!picking)return;const el=document.elementFromPoint(e.clientX,e.clientY);if(!el||el===host)return;e.preventDefault();e.stopImmediatePropagation();select(el);},{capture:true,signal});
  document.addEventListener('keydown',e=>{if(!active)return;if(e.key==='Escape'){cancel();stopPick();menu(false);q('.window').hidden=true;q('.toolbar').hidden=true;q('.mascot').focus();}if(!own(e)&&phase==='selected'&&!['INPUT','TEXTAREA','SELECT'].includes((e.target as Element)?.tagName)&&(e.key==='ArrowUp'||e.key==='ArrowDown')){const el=e.key==='ArrowUp'?selected?.parentElement:selected?.firstElementChild;if(el&&el!==host){e.preventDefault();select(el);}}},{capture:true,signal});
  q('.mascot').onclick=()=>menu(!q('.launcher').classList.contains('open'));
  q('.launcher').addEventListener('pointerenter',()=>clearTimeout(menuTimer),{signal});
  q('.launcher').addEventListener('pointerleave',()=>{menuTimer=setTimeout(()=>{if(!root.activeElement?.matches(':focus-visible'))menu(false);},300);},{signal});
  q('.launcher').addEventListener('focusout',()=>{menuTimer=setTimeout(()=>{if(!q('.launcher').contains(root.activeElement))menu(false);},150);},{signal});
  window.addEventListener('scroll',geometry,{capture:true,passive:true,signal});window.addEventListener('resize',()=>{drag=null;Object.assign(q('.window').style,{left:'',top:'',right:'',bottom:''});geometry();},{signal});
  async function scan(){if(!selected?.isConnected){notify('Selection is unavailable. Pick again.');return;}cancel();const version=run;suppressResult=false;stopPick();phase='scanning';q('.toolbar').hidden=true;q('.window').hidden=true;geometry();q('.scan').hidden=false;q('.scan-label').hidden=false;q('.scan-label').textContent='Reading computed styles…';
    await new Promise(resolve=>setTimeout(resolve,40));if(version!==run||destroyed)return;
    try{const snapshot=measureElement(selected);await new Promise(resolve=>setTimeout(resolve,900));if(version!==run||destroyed)return;facts=snapshot;phase='result';q('.scan').hidden=true;q('.scan-label').hidden=true;if(!suppressResult)lesson();}catch{cancel();notify('Measurement failed. Pick another element to retry.');}}
  function show(body:string,footer:string,wide=false){q('.body').innerHTML=body;q('.foot').innerHTML=footer;q('.window').classList.toggle('wide',wide);q('.window').hidden=false;menu(false);}
  const rows=(values:[string,unknown][])=>`<dl>${values.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`;
  function lesson(){if(!facts){show('<h2>Every website has something to teach you.</h2><p>Pick a detail. Scan its real styles. Save what you learn.</p>','<button class="primary" data-action="pick">Pick an element</button>');return;}const f=facts,c=f.color.contrast;show(`<h2>${scope==='page'?'Page selection':esc(f.a11y.accessibleName.value||f.structure.componentType.value||f.structure.tag.value)}</h2><p class="muted">${esc(new URL(f.url).hostname)} · ${esc(new Date(f.capturedAt).toLocaleString())}</p><span class="badge">Measured</span>
      <h3>Typography</h3>${rows([['Family',f.typography.fontFamily.value],['Size / weight',`${f.typography.fontSize.value}px / ${f.typography.fontWeight.value}`],['Line height',f.typography.lineHeight.value??'normal'],['Tracking',`${f.typography.letterSpacing.value}px`]])}
      <h3>Color</h3>${rows([['Text',f.color.text.value],['Background',f.color.background.value],['Contrast',c.canMeasure?`${c.ratio}:1 · AA ${c.aa?'pass':'fail'} · AAA ${c.aaa?'pass':'fail'}`:`Can't measure: ${c.reason}`]])}
      <h3>Spacing & structure</h3>${rows([['Padding',f.spacing.padding.value.join(' ')+' px'],['Margin',f.spacing.margin.value.join(' ')+' px'],['Bounds',`${f.size.width.value} × ${f.size.height.value}px`],['Radius',f.shape.borderRadius.value.join(' ')+' px'],['Layout',f.layout.display.value],['Role',f.structure.role.value??'Not declared'],['Matching styles',f.consistency.sameStyleCount.value]])}
      <h3><span class="badge inferred">Inferred</span> Design lesson</h3><p class="muted">AI interpretation is not connected yet. These measurements are real; capture and model integration belong in the analysis adapter.</p>${scope==='page'?'<p class="muted">Page scope currently measures the body element. Aggregate inventory and full-page capture are pending.</p>':''}`,'<button data-action="pick">Pick another</button><button data-action="export">Export</button><button class="primary" data-action="save">Save idea</button>');}
  async function save(){if(!facts)return;const item:Saved={id:`${facts.url}|${facts.selector}`,title:facts.a11y.accessibleName.value||facts.structure.componentType.value||facts.structure.tag.value,scope,facts};if(saved.some(i=>i.id===item.id)){notify('Already in your saved ideas.');return;}const next=[...saved,item];try{await chrome.storage.local.set({[key]:next});saved=next;clearTimeout(poseTimer);q('.launcher').classList.add('collected');notify('Idea stolen. Source credited. Saved!');poseTimer=setTimeout(()=>q('.launcher').classList.remove('collected'),2800);}catch{notify('Could not save. Your measurements are still available to export.');}}
  function library(){compare=compare.filter(id=>saved.some(i=>i.id===id));show(`<h2>Saved ideas</h2>${saved.length?saved.map(i=>`<div class="saved-item"><input type="checkbox" aria-label="Compare ${esc(i.title)}" data-compare="${esc(i.id)}" ${compare.includes(i.id)?'checked':''}><button data-open="${esc(i.id)}">${esc(i.title)}<p class="muted">${esc(new URL(i.facts.url).hostname)} · ${i.scope}</p></button></div>`).join(''):'<p>Your first idea starts with a selection.</p>'}`,'<button data-action="pick">Pick an element</button><button class="primary" data-action="compare" '+(compare.length<2?'disabled':'')+'>Compare ('+compare.length+'/3)</button>');}
  function chosen(){return saved.filter(i=>compare.includes(i.id));}
  function values(items:Saved[]){const get=(category:string)=>items[Math.min(sources[category]||0,items.length-1)].facts;return {font:get('Typography').typography,color:get('Color').color,radius:get('Shape').shape.borderRadius.value,padding:get('Spacing').spacing.padding.value};}
  function output(items:Saved[]){const t=values(items);const provenance=items.map(i=>({url:i.facts.url,selector:i.facts.selector,capturedAt:i.facts.capturedAt}));if(format==='json')return JSON.stringify({label:'Measured',sources:provenance,borrowedFrom:sources,tokens:{fontFamily:t.font.fontFamily.value,fontSize:t.font.fontSize.value,color:t.color.text.value,background:t.color.background.value,radius:t.radius,padding:t.padding},inferred:[]},null,2);if(format==='css')return `/* Measured values. Sources: ${provenance.map(i=>i.url.replace(/\*\//g,'')).join(', ')} */\n:root {\n --font-family: ${t.font.fontFamily.value};\n --font-size: ${t.font.fontSize.value}px;\n --color-text: ${t.color.text.value};\n --color-background: ${t.color.background.value};\n --radius: ${t.radius.map(v=>v+'px').join(' ')};\n --padding: ${t.padding.map(v=>v+'px').join(' ')};\n}`;return `# Design direction\n\n## Measured\n- Font: ${t.font.fontFamily.value}, ${t.font.fontSize.value}px\n- Color: ${t.color.text.value} on ${t.color.background.value}\n- Radius: ${t.radius.join(' ')}px\n- Padding: ${t.padding.join(' ')}px\n\n## Sources\n${provenance.map(i=>`- ${i.url} · ${i.selector} · ${i.capturedAt}`).join('\n')}\n\n## Inferred\nAI interpretation not connected.\n`;}
  let exportItems:Saved[]=[];
  function direction(items:Saved[]){if(!items.length)return;exportItems=items;const groups=['Typography','Color','Shape','Spacing'];show(`<h2>${items.length>1?'Compare & borrow':'Design direction'}</h2>${items.length>1?`<table><thead><tr><th>Measured</th>${items.map((i,n)=>`<th>${'ABC'[n]} · ${esc(i.title)}</th>`).join('')}</tr></thead><tbody>${[['Font size',(f:Facts)=>f.typography.fontSize.value+'px'],['Color',(f:Facts)=>f.color.text.value],['Radius',(f:Facts)=>f.shape.borderRadius.value.join(' ')+'px']].map(([title,get])=>`<tr><th>${title}</th>${items.map(i=>`<td>${esc((get as (f:Facts)=>string)(i.facts))}</td>`).join('')}</tr>`).join('')}</tbody></table><h3>What to borrow</h3>${groups.map(g=>`<fieldset><legend>${g}</legend>${items.map((_,n)=>`<label><input type="radio" name="${g}" value="${n}" ${Math.min(sources[g]||0,items.length-1)===n?'checked':''}>${'ABC'[n]}</label>`).join('')}</fieldset>`).join('')}`:''}<div class="formats">${(['md','json','css'] as const).map(f=>`<button data-format="${f}" class="${format===f?'active':''}">${{md:'DESIGN.md',json:'tokens.json',css:'CSS'}[f]}</button>`).join('')}</div><pre>${esc(output(items))}</pre>`,'<button data-action="saved">Saved</button><button class="primary" data-action="download">Download</button><button data-action="pick">Pick another</button>',items.length>1);}
  root.addEventListener('change',e=>{const input=e.target as HTMLInputElement;if(input.dataset.compare){if(input.checked&&compare.length>=3){input.checked=false;notify('Compare up to three ideas.');return;}compare=input.checked?[...compare,input.dataset.compare]:compare.filter(id=>id!==input.dataset.compare);library();}else if(input.type==='radio'){sources[input.name]=Number(input.value);direction(exportItems);}}, {signal});
  root.addEventListener('click',e=>{const target=(e.target as Element).closest<HTMLElement>('button');if(!target)return;const action=target.dataset.action;if(target.dataset.open){const item=saved.find(i=>i.id===target.dataset.open);if(item){facts=item.facts;scope=item.scope;lesson();}return;}if(target.dataset.format){format=target.dataset.format as typeof format;direction(exportItems);return;}switch(action){case'pick':pick();break;case'page':select(document.body,true);break;case'scan':void scan();break;case'parent':if(selected?.parentElement)select(selected.parentElement);break;case'child':if(selected?.firstElementChild)select(selected.firstElementChild);break;case'clear':cancel();selected=null;facts=null;stopPick();place(q('.selected'),null);q('.toolbar').hidden=true;break;case'hide':suppressResult=true;q('.window').hidden=true;break;case'resume':if(phase==='scanning'){suppressResult=false;show('<h2>Reading computed styles</h2><p class="muted">Your selected element is being measured.</p>','<button data-action="hide">Hide</button>');}else lesson();break;case'saved':if(phase==='scanning')suppressResult=true;library();break;case'save':void save();break;case'compare':if(compare.length>=2)direction(chosen());break;case'export':if(facts)direction([{id:'current',title:facts.structure.tag.value,scope,facts}]);break;case'download':{const blob=new Blob([output(exportItems)],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download={md:'DESIGN.md',json:'tokens.json',css:'variables.css'}[format];a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}}},{signal});
  let drag:{x:number;y:number;left:number;top:number}|null=null;
  q('.handle').addEventListener('pointerdown',e=>{const r=q('.window').getBoundingClientRect();drag={x:e.clientX,y:e.clientY,left:r.left,top:r.top};q('.handle').setPointerCapture(e.pointerId);},{signal});
  q('.handle').addEventListener('pointermove',e=>{if(!drag)return;Object.assign(q('.window').style,{left:`${Math.max(8,Math.min(innerWidth-q('.window').offsetWidth-8,drag.left+e.clientX-drag.x))}px`,top:`${Math.max(8,Math.min(innerHeight-q('.window').offsetHeight-8,drag.top+e.clientY-drag.y))}px`,right:'auto',bottom:'auto'});},{signal});
  q('.handle').addEventListener('pointerup',()=>drag=null,{signal});
  return {activate(){active=true;host.hidden=false;host.style.display='block';},pick(){active=true;host.hidden=false;host.style.display='block';pick();},deactivate(){active=false;cancel();stopPick();host.hidden=true;host.style.display='none';},destroy(){destroyed=true;cancel();abort.abort();clearTimeout(menuTimer);clearTimeout(feedbackTimer);clearTimeout(poseTimer);host.remove();}};
}
